### PR TITLE
Time to JSON!

### PR DESCRIPTION
**Pull request by TheSilkMiner**
> _Data is data, we dont give a shit how you make that data._
> _\- LexManos_

What this mod does is adding information for various different mods to their JustEnoughItems tab. The goal of this pull request is to ease this addition by using a JSON-based system instead of pure code and checks.

### What does not change
Even if these additions (and deletions) happen in various different places, there are some things that don't change. One of them is the content: what was said before is said now too. There are literally no changes, additions or deletion to that. Another one is the topics that are covered: same mods, same items, same functionalities, just in a different place.

### What does change
Of course there are a lot of changes in how that content is loaded: first of all it is no more loaded from the language file directly with in-game calls but from a JSON-based registry (not a `ForgeRegistry` though) that automatically manages the loading and the registering for the various mods. Not only that: no checks need to be performed anymore since the system is entirely based on the actual mods that are present in the instance.
Another change is the removal of the dependency on Quark when compiling since all the calls are performed through reflection. This does not have a hard impact on the gameplay since it is done at loading time, and the JIT can optimize the call if it deems necessary to do so. Profiling with the `ProgressManager` says that the current amount of JSON files (almost 300) loads in less than half a second.
Last but not least, the JSON system also allows to load up NBT-based `ItemStack`s, in case they're needed for some special cases.

### Workflow example
Suppose that there exists a mod `examplemod` that adds the item `exampleitem` and the modder wants to document the one identified by the metadata `2` in two different languages and add a tooltip with some text colored in blue.
1) Create a directory in assets called `examplemod` and then create the `dym` directory in it.
2) Create a new JSON file with the name `exampleitem_meta_two.json` (name is arbitrary).
3) Add the following lines to it.

<details><summary>JSON code</summary>

```json
{
  "conditions": [
    {
      "type": "dym:configuration_option",
      "name": "useExampleMod",
      "value": true
    }
  ],
  "for": [
    {
      "type": "dym:item",
      "registry_name": "examplemod:exampleitem",
      "metadata": 2
    }
  ],
  "documentation": [
    "dym.doc.examplemod.exampleitem"
  ],
  "tooltip": [
    {
      "key": "dym.tip.examplemod.exampleitem",
      "formatting": "blue"
    }
  ]
}
```

</details>

4) Add to all the language file the string `dym.doc.examplemod.exampleitem=Cool Description!` with the various translations.
5) Repeat the process for the string `dym.tip.examplemod.exampleitem=An even cooler Tooltip!`

And that's done: the registry JSON will automatically add the information to JEI.

### CODE REVIEW

**Comment by aaronhowser1** [comment]
Woah, this had a ton of effort put into it! I'm going to spend a bit of time reading through it because I have absolutely no idea what I'm looking at yet

**Comment by TheSilkMiner** [comment]
Of course, take your time and feel free to add some comments or reviews if something is unclear or you have some requests/advice

**Comment by aaronhowser1** [comment]
Just a couple questions before merging:

- Have you built the jar and tested it in a modpack?
- Does NBT finally work (TiCon tools and Quark's enchanted books)?
- Ideally, if there are no bugs and I don't want any new features and just wanted to support more mods, would I just have to add a config option and then a new folder in that mod's assets and then a json for each item?
- Is it possible to also add a way to add tooltips? That would be especially useful for short descriptions, so if you searched "biome" in JEI you'd be able to see Nature's Compass if I added a tooltip like "Finds biomes" to it

**Comment by TheSilkMiner** [comment]
1) Sincerely no, because I do not have a production environment set up for 1.12.2 at the moment.
2) It should. Bigger explanation below.
3) Yep. Not necessarily for each item, but a JSON file for each functionality you want to document.
4) It is possible, since the JSON format used can be extended. This is not in the scope of this PR but I could take a look at it if you want and submit a different one. Or if you want to attempt it yourself, too.

### The question with NBT
NBT can be deserialized from JSON, according to the code, so this should not be an issue. What I don't know is whether it works in-game because I don't know what NBT tags Tinkers' Construct uses to differentiate between the various items and the like. If you want and could give me a tip, I could test it out and see what happens.

**Comment by LatvianModder** [comment]
I think the idea to make mod data-driven is good, but this is a bit of overkill. And to put multiple languages in same file is not a good idea, it makes pull requests more complicated. I always thought it should be part of JEI, but It should be one bigass file:

```json
[
  {"item": "mod:itemid", "description": "jei.description.key"},
  {"item": "mod:itemid", "data": 2, "description": "jei.description.key"},
  {"ore_name": "treeSapling", "description": "jei.description.key"}
]
``` 

And descriptions would go in language files as they normally would

**Comment by TheSilkMiner** [comment]
Now that I think about it, I agree with the aspect of multiple languages: I am moving them back to the `lang` file.
Having a huge file though it seems a bit too much for me, because if you have to change something quickly, it helps having smaller files, each one that looks at a certain feature and nothing else

**Comment by TheSilkMiner** [comment]
Little update: NBT-based items are now supported

**Comment by aaronhowser1** [comment]
`Sincerely no, because I do not have a production environment set up for 1.12.2 at the moment.`

Is it possible for me to try building this before merging into the main branch?

**Comment by aaronhowser1** [comment]
[What exactly is happening here?](https://github.com/aaronhowser1/Document-Your-Mod-Mod/pull/1/commits/7a6de165489c4eccf77c9d64cb5f058f2845c60c) You have a "translation checker" in OpenMods' third party maven and you're calling it, but what does it do? `This will allow to check all the translations and mark them for an update whenever new documented items are added to the mod` is what the commit says, but how would I know that something is marked for an update?

**Comment by aaronhowser1** [comment]
[This commit looks like it has a specific class for each mod that has NBT stuff](https://github.com/aaronhowser1/Document-Your-Mod-Mod/pull/1/commits/dcaf61817d28bf73d4e6f9bcd146a6dd2c180a67). Would I need to make another for every mod that gets support if it has NBT stuff I want to document? 

`"type": "quark:enchantment_book" `, but it's still Vanilla's Enchanted Books that are being changed by Quark, does that matter?

```json
      "type": "tconstruct:nbt_tool",
      "registry_name": "tconstruct:cleaver"
```
If I wanted to add documentation to the *blocks* of TiCon that had NBT, like the Tool Forge or Stencil Table, would I do
```json
      "type": "tconstruct:nbt_tool",
      "registry_name": "tconstruct:toolforge"
```
and just it would apply it to all Tool Forges regardless of NBT? Would it be the same if I wanted to document each tool part and have it show for all materials?

**Comment by TheSilkMiner** [comment]
> Is it possible for me to try building this before merging into the main branch?

Yes, you can use the following two commands to fetch a copy of my code onto your computer without touching your code on the `master` branch:
```posh
git fetch origin pull/1/head:pull-request-1
git checkout pull-request-1
```

> What exactly is happening here? You have a "translation checker" in OpenMods' third party maven and you're calling it, but what does it do? 

This tool is something that was written for the OpenMods' set of mods, that's the reason why I'm pulling it from there. Anyway it is a tool that automatically checks the `assets/<mod-id>/lang` directory for language files and synchronizes the other languages with the `en_us.lang` one. In other words, if you delete an entry from `en_us.lang`, it gets automatically deleted from the other language files. If you add something it gets automatically added to the other files and those are marked for update (i.e. a `### NEEDS TRANSLATION ###` text is added after the language entry. I'll provide an example later on.
Those two tasks you see are simply added: they are not run automatically because that's the way the plugin was coded. To run them you can simply execute the respective gradle task: `./gradlew updateTranslations` and `./gradlew checkTranslations`.
If you don't want it, I can delete the commit.

<details><summary>Example</summary>

Let's pretend that you have some lines in the `en_us.lang` and somebody translated the entirety of it in German, creating a `de_de.lang` file.
Let's now suppose you add a new line to `en_us.lang`, let's say on line 53 that says `dym.doc.quark.iron_chain=Iron Chains are something awesome`.
When you run the `updateTranslations` task, the tool will automatically read the `en_us.lang` file and notice this addition. It will subsequently add a new line to `de_de.lang`, exactly at the same position with the same content and the update marker. In other words, if you'd go to `de_de.lang` you'd see on line 53 the following: `#dym.doc.quark.iron_chain=Iron Chains are something awesome ### NEEDS TRANSLATION ###`.

</details>

> This commit looks like it has a specific class for each mod that has NBT stuff. Would I need to make another for every mod that gets support if it has NBT stuff I want to document?

You don't have to as long as the mod follows one of the two methods that are already provided.
`quark:enchantment_book` automatically grabs the vanilla Enchanted Book and all of the variants added through NBT. This one is not configurable.
`tconstruct:nbt_tool` works for every mod that shows a set of NBT items in its own Creative Tab. In other words, if you open its creative tab and see items that vary only due to NBT you can use `tconstruct:nbt_tool` and the registry name even if the mod is not Tinkers' Construct.

Those names were chosen only because I wrote those two `StackFactory`es to satisfy the needs of those two mods, but nothing blocks you from using it for other mods that follow the same mechanism.

> `"type": "quark:enchantment_book"` , but it's still Vanilla's Enchanted Books that are being changed by Quark, does that matter?

It's just a name. You can change it to another namespace if you want: it is basically an identifier that I chose to add to Quark's namespace because I used it in files from the Quark mod.

> If I wanted to add documentation to the blocks of TiCon that had NBT, like the Tool Forge or Stencil Table, would I do [...] and just it would apply it to all Tool Forges regardless of NBT?

Yes, exactly.

> Would it be the same if I wanted to document each tool part and have it show for all materials?

As long as tool parts follow the same mechanism, yes. In other words, if you can see the various tool parts in the Creative Tab, it works without issues.

**Comment by aaronhowser1** [comment]
I switched over to the PR branch and tried runClient in IDEA and it gave me [this crash](https://pastebin.com/x3TvsTk0)

**Comment by TheSilkMiner** [comment]
Woops, my issue. Wrong method call

**Comment by aaronhowser1** [comment]
Didn't crash this time, and it looks like pretty much everything except Enchanted Books work, including TiCon stuff which is great.

**Comment by TheSilkMiner** [comment]
Enchanted Books not working is weird: in my instance (in-dev) it works perfectly.
But yeah, now it's just a matter of reading logs and debugging
image

**Comment by aaronhowser1** [comment]
image
[My console output](https://pastebin.com/24CcajvG)
[My latest.log](https://pastebin.com/SM08WtYQ)
[My debug.log](https://github.com/aaronhowser1/Document-Your-Mod-Mod/files/3424049/debug.log)

**Comment by TheSilkMiner** [comment]
Do you have Quark loaded?
```log
[15:52:06] [main/INFO] [FML]: Searching C:\Users\aaron\Desktop\Games\Minecraft modding\Document-Your-Mod-Mod\run\.\mods for mods
[15:52:06] [main/DEBUG] [FML]:   Adding Mantle-1.12-1.3.3.55.jar to the mod list
[15:52:06] [main/DEBUG] [FML]:   Adding NaturesCompass-1.12.2-1.5.1.jar to the mod list
[15:52:06] [main/DEBUG] [FML]:   Adding refinedstorage-1.6.14.jar to the mod list
[15:52:06] [main/DEBUG] [FML]:   Adding refinedstorageaddons-0.4.4.jar to the mod list
[15:52:06] [main/DEBUG] [FML]:   Adding TConstruct-1.12.2-2.12.0.157.jar to the mod list
[15:52:06] [main/DEBUG] [FML]:   Adding TipTheScales-1.12.2-1.0.4.jar to the mod list
[15:52:06] [main/DEBUG] [FML]:   Adding twilightforest-1.12.2-3.8.689-universal.jar to the mod list
[15:52:06] [main/DEBUG] [FML]:   Adding Waystones_1.12.2-4.0.67.jar to the mod list
[15:52:06] [main/DEBUG] [FML]: Examining for coremod candidacy Mantle-1.12-1.3.3.55.jar
```

**Comment by aaronhowser1** [comment]
Ha, yeah that was the issue. I forgot that you took quark out of the gradle thing so I didn't have it in my /run/mods/. It worked when I actually installed it. At least we know it works without quark still :P

The only things I want to know before merging this:

- Can you please add a way to let me add tooltips, that way I could add small descriptions that have key words people might search for (again, like searching "biome" and seeing Nature's Compass) (this would probably have to be a different json too, right? you said a json per `each functionality you want to document`)
- Can you generalize the `tconstruct:nbt_tool` to be more like `dym:item_ignore_nbt` or something? that way it won't look weird if I want to document something that *isn't* from TiCon but still has wonky NBT stuff.
- What is your Twitch/CurseForge profile name? You've basically completely overhauled the mod, so you 100% deserve a cut of the CF points it makes.

**Comment by TheSilkMiner** [comment]
> Can you please add a way to let me add tooltips, that way I could add small descriptions that have key words people might search for

Addressed.

> (this would probably have to be a different json too, right? you said a json per `each functionality you want to document`)

Not necessarily: as you see with the Nature's Compass you can add a tooltip to basically every JSON you want. You need to create a new JSON file if you want to add a tooltip to an item that is not yet documented or that is documented in a group and you don't want that (e.g. a specific type of banner).

> Can you generalize the `tconstruct:nbt_tool` to be more like `dym:item_ignore_nbt` or something? that way it won't look weird if I want to document something that isn't from TiCon but still has wonky NBT stuff.

Addressed. You now have `dym:enchanted_book` for enchanted books and `dym:item_all_nbt_in_search` for items that follow the Tinkers' Construct method of showing NBT (which I've already covered in the message above).

> What is your Twitch/CurseForge profile name? You've basically completely overhauled the mod, so you 100% deserve a cut of the CF points it makes.

It would be an honor, if you wanted to. My username is the same on all platforms, so @TheSilkMiner. 

### One little concern
I am leaving in a few hours, so I won't have access to my development computer for at least three weeks and the laptop I'll bring with me cannot handle Minecraft. For this reason, I don't think I'll be able to edit the code a lot if needed: I'll probably be able to change one or two lines here and there but that's it. In any case, I'll always be reachable on Discord in case you have some questions or... for basically anything else. I'm `Silk` in the ModdedMC server.

**Comment by aaronhowser1** [comment]
```json
{
  "conditions": [
    {
      "type": "dym:configuration_option",
      "name": "useTinkersConstruct",
      "value": true
    }
  ],
  "for": [
    {
      "type": "dym:item_all_nbt_in_search",
      "registry_name": "tconstruct:tooltables",
      "metadata": 1
    }
  ],
  "documentation": [
    "dym.doc.tconstruct.stencil_table"
  ]
}
```

I tried using that json to add a description to the Stencil Table, but it adds it to all `tconstruct:tooltables` instead of just `tconstruct:tooltables:1`.

**Pull request merged**
